name: relic
main: net\orange\soeur\relic\Main
version: 1.0.0
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.1
- 4.0.0
- 5.0.0
author: Orange
description: 橘子的遗迹插件

permissions:
 relic.command.re:
  description: "relic遗迹插件指令"
  default: op